version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.12
executors:
  default:
    docker:
      - image: circleci/node:12.5.0-browsers
      - image: circleci/python:2.7
jobs:
  build:
    executor: default
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "./package.json" }}
            - node-v1-

      - run:
          command: npm install

      - save_cache:
          key: node-v1-{{ checksum "./package.json" }}
          paths:
            - ./node_modules

      - run:
          name: UnitTest
          command: npm run test:unit
      
  deploy:
    executor: default
    steps:
      - checkout
      - run:
          command: npm install 
      - run:
          command: npm run build
      - aws-s3/copy:
          from: ./dist
          to: 's3://aws-learning.com'
          arguments: '--recursive'
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master