version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.5.0-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "./src/package.json" }}
            - node-v1-

      - run:
          command: npm install

      - save_cache:
          key: node-v1-{{ checksum "./src/package.json" }}
          paths:
            - ./src/node_modules

      - run:
          name: UnitTest
          command: npm run test:unit
      
      - run:
          command: npm run build
orbs:
  aws-s3: circleci/aws-s3@1.0.0
workflows:
  s3-deploy:
    jobs:
      - build
      - aws-s3/sync:
          from: ./dist
          to: 's3://aws-learning.com'
          overwrite: true