version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.12
jobs:
  build:
    docker:
      - image: circleci/node:12.5.0-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "./src/package.json" }}
            - node-v1-

      - run:
          command: npm install

      - save_cache:
          key: node-v1-{{ checksum "./src/package.json" }}
          paths:
            - ./src/node_modules

      - run:
          name: UnitTest
          command: npm run test:unit
      
      - run:
          command: npm run build
  deploy:
    docker:
      - image: 'circleci/python:3.6'
    steps:
      - checkout
      - aws-s3/copy:
          from: ./src/dist
          to: 's3://aws-learning.com'
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master